version: "3"
services:
  mongodb:
    image: mongo
    container_name: mern_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - db-volume:/data/db

  redis:
    image: redis:6.2-alpine
    container_name: mern_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/data/redis

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mern_api
    ports:
      - "5009:5000"
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017/
      - PORT=5000
      - JWT_SECRET=SECRET
      - REDIS_URL=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mern_app
    ports:
      - "6601:80"
    restart: always

volumes:
  db-volume:
